solve(Faraon, Mama, Hijo, Hija, Robot, Sacerdote, Demis, Vangelis, Mikis, Wilson, Akerfeldt, Parsons, Gilmour, Dickinson, Harris, Dio, Summers) :-
    L = [1, 2, 3],
    member(Faraon, L),
    member(Mama, L),
    member(Hijo, L),
    member(Hija, L),
    member(Robot, L),
    member(Sacerdote, L),
    member(Demis, L),
    member(Vangelis, L),
    member(Mikis, L),
    member(Wilson, L),
    member(Akerfeldt, L),
    member(Parsons, L),
    member(Gilmour, L),
    member(Dickinson, L),
    member(Harris, L),
    member(Dio, L),
    member(Summers, L),
    Faraon = Mama,
    Faraon = Hijo,
    Faraon = Hija,
    Faraon = Robot,
    Demis = Vangelis, 
    Demis = Mikis,
    Wilson = Akerfeldt,
    Demis = Wilson,
    Parsons = Gilmour,
    Wilson \= Parsons,
    Sacerdote \= Faraon,
    Sacerdote \= Harris,
    Sacerdote \= Robot,
    Sacerdote \= Dickinson,
    Sacerdote \= Dio,
    Sacerdote \= Summers,
    Total is Faraon + Mama + Hijo + Hija + Robot + Sacerdote + Demis + Vangelis + Mikis + Wilson + Akerfeldt + Parsons + Gilmour + Dickinson + Harris + Dio + Summers,
    Total = 35,
    !.
